### ISSUE TITLE
Failed to compile after pull

### ISSUE THREAD

**Issue by bmlancien** [destacks/react-examples#1]
My first issue here :)

I get this error after i pulled and did `npm run dev`

Did I forget to do something?

pages/_layout.jsx
An error occured in `next/font`.

Error: Cannot find module 'tailwindcss'
Require stack:
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/blocks/css/index.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/index.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack-config.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/server/dev/hot-reloader.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/server/next.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/server/lib/render-server.js
- /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/server/require-hook.js:113:36
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at loadPlugin (/Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:54:32)
    at /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:162:56
    at Array.map (<anonymous>)
    at getPostCssPlugins (/Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:162:47)
    at async /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/config/blocks/css/index.js:124:36
    at async /Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js:51:41
    at async Span.traceAsyncFn (/Users/bryanlancien/Documents/Freelance/Code/react-examples/node_modules/next/dist/trace/trace.js:103:20)

**Comment by 4lm** [comment]
I added new dependencies to the project. First try `npm install`, then `npm run dev` should work!

**Comment by bmlancien** [comment]
Looks good. Thanks for the help :)
